/*
 * (C) Copyright IBM Corp. 2022.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package com.ibm.cloud.eventnotifications.event_notifications.v1.model;

import java.util.List;

import com.google.gson.annotations.SerializedName;
import com.ibm.cloud.sdk.core.service.model.GenericModel;

/**
 * Topic list item object.
 */
public class TopicsListItem extends GenericModel {

  protected String id;
  protected String name;
  protected String description;
  @SerializedName("source_count")
  protected Long sourceCount;
  @SerializedName("sources_names")
  protected List<String> sourcesNames;
  @SerializedName("subscription_count")
  protected Long subscriptionCount;

  /**
   * Gets the id.
   *
   * Autogenerated topic ID.
   *
   * @return the id
   */
  public String getId() {
    return id;
  }

  /**
   * Gets the name.
   *
   * Name of the topic.
   *
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * Gets the description.
   *
   * Description of the topic.
   *
   * @return the description
   */
  public String getDescription() {
    return description;
  }

  /**
   * Gets the sourceCount.
   *
   * Number of sources.
   *
   * @return the sourceCount
   */
  public Long getSourceCount() {
    return sourceCount;
  }

  /**
   * Gets the sourcesNames.
   *
   * List of source names.
   *
   * @return the sourcesNames
   */
  public List<String> getSourcesNames() {
    return sourcesNames;
  }

  /**
   * Gets the subscriptionCount.
   *
   * Number of subscriptions.
   *
   * @return the subscriptionCount
   */
  public Long getSubscriptionCount() {
    return subscriptionCount;
  }
}

